# http://blog.onk.ninja/2015/10/27/rubocop-getting-started
# https://github.com/onk/onkcop/blob/master/config/rubocop.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/AsciiComments:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

MethodLength:
  Max: 12
